[package]
name = "bb-gradebook"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "2.2.0"
regex = "1.11.0"
chrono = "0.4.38"
thiserror = "1.0.64"
